services:
  - type: web
    name: astro-vending-machine
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn vending_machine.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:dVKNyGgZRCgOzaxvwoIWWkHTgzeHMQPT@trolley.proxy.rlwy.net:57726/railway
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: astro-database
    plan: free