# Generated by Django 5.2.7 on 2025-10-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
                ('max_stock', models.IntegerField(default=50)),
                ('min_stock', models.IntegerField(default=5)),
                ('category', models.CharField(choices=[('snacks', 'Snacks'), ('drinks', 'Drinks')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], default='purchase', max_length=20)),
                ('rs1', models.IntegerField(default=0)),
                ('rs5', models.IntegerField(default=0)),
                ('rs10', models.IntegerField(default=0)),
                ('rs20', models.IntegerField(default=0)),
                ('rs25', models.IntegerField(default=0)),
                ('rs50', models.IntegerField(default=0)),
                ('rs100', models.IntegerField(default=0)),
                ('rs200', models.IntegerField(default=0)),
                ('change_rs1', models.IntegerField(default=0)),
                ('change_rs5', models.IntegerField(default=0)),
                ('change_rs10', models.IntegerField(default=0)),
                ('change_rs20', models.IntegerField(default=0)),
                ('change_rs25', models.IntegerField(default=0)),
                ('change_rs50', models.IntegerField(default=0)),
                ('change_rs100', models.IntegerField(default=0)),
                ('change_rs200', models.IntegerField(default=0)),
                ('products_purchased', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.product')),
            ],
            options={
                'unique_together': {('session_key', 'product')},
            },
        ),
    ]
