# Generated by Django 5.2.7 on 2025-10-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_rs1', models.IntegerField(default=0)),
                ('change_rs5', models.IntegerField(default=0)),
                ('change_rs10', models.IntegerField(default=0)),
                ('change_rs20', models.IntegerField(default=0)),
                ('change_rs25', models.IntegerField(default=0)),
                ('change_rs50', models.IntegerField(default=0)),
                ('change_rs100', models.IntegerField(default=0)),
                ('change_rs200', models.IntegerField(default=0)),
                ('products_purchased', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyInsertion',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_change', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], default='purchase', max_length=20)),
                ('rs1', models.IntegerField(default=0)),
                ('rs5', models.IntegerField(default=0)),
                ('rs10', models.IntegerField(default=0)),
                ('rs20', models.IntegerField(default=0)),
                ('rs25', models.IntegerField(default=0)),
                ('rs50', models.IntegerField(default=0)),
                ('rs100', models.IntegerField(default=0)),
                ('rs200', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='moneychange',
            name='money_insertion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='change_details', to='vm_app.moneyinsertion'),
        ),
    ]
