# Generated by Django 5.2.7 on 2025-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0002_moneychange_moneyinsertion_delete_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyinsertion',
            name='products_purchased',
            field=models.TextField(blank=True, null=True),
        ),
    ]
