# Generated by Django 5.2.7 on 2025-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0003_moneyinsertion_products_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs10',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs100',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs20',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs200',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs25',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyinsertion',
            name='rs50',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
